language: elixir
elixir:
  - 1.3.4
  - 1.4.0
  - 1.5.1
otp_release:
  - 18.3
  - 19.2
  - 20.1

matrix:
  exclude:
    - elixir: 1.3.4
      otp_release: 20.1

sudo: false

before_script:
  - MIX_ENV=test mix do deps.get
script:
  - MIX_ENV=test mix test
after_script:
  - MIX_ENV=test mix coveralls.travis
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
